In [17]:
import csv
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import pandas as pd

def calculate_similarity(data):
    # 데이터를 데이터 프레임으로 변환
    data = pd.DataFrame(data).iloc[1:,1:]

    # TF-IDF 벡터화
    # vectorizer = TfidfVectorizer()
    # tfidf_matrix = vectorizer.fit_transform(data)

    # 코사인 유사도 계산
    # similarity_matrix = cosine_similarity(tfidf_matrix, tfidf_matrix)
    similarity_matrix = cosine_similarity(data, data)

    return similarity_matrix

# CSV 파일 읽기
data = []
with open('원본_0613_cluster6_vectors.csv', 'r') as csvfile:
    reader = csv.reader(csvfile)
    for row in reader:
        data.append(row)

# 행별 유사도 계산(1번 군집 기준 : 1604 * 1604)
similarity_matrix = calculate_similarity(data)

# 유사한 인덱스 추출
n_similar_indices = 6  # 유사한 인덱스 개수
similar_indices = []
for i, row in enumerate(similarity_matrix):
    top_indices = np.argsort(-row)[0:n_similar_indices+1]  # 가장 유사한 인덱스 추출 (자기 자신은 제외)
    similar_indices.append(top_indices)

# 결과 출력
for i, indices in enumerate(similar_indices):
    print(f"인덱스 {i}과 가장 유사한 {n_similar_indices}개 인덱스:")
    for index in indices:
        print(index)

인덱스 0과 가장 유사한 6개 인덱스:
0
757
1891
410
678
1609
1733
인덱스 1과 가장 유사한 6개 인덱스:
1
1994
581
549
495
602
1143
인덱스 2과 가장 유사한 6개 인덱스:
2
895
120
365
1542
271
788
인덱스 3과 가장 유사한 6개 인덱스:
3
20
1602
1144
1854
146
1896
인덱스 4과 가장 유사한 6개 인덱스:
4
1118
775
1119
1706
1657
301
인덱스 5과 가장 유사한 6개 인덱스:
5
1941
1002
382
1893
1556
618
인덱스 6과 가장 유사한 6개 인덱스:
6
814
137
1561
248
121
645
인덱스 7과 가장 유사한 6개 인덱스:
7
1527
872
1944
484
1436
1582
인덱스 8과 가장 유사한 6개 인덱스:
8
1223
1449
730
857
921
451
인덱스 9과 가장 유사한 6개 인덱스:
9
602
1858
332
919
12
1693
인덱스 10과 가장 유사한 6개 인덱스:
10
1823
1612
1832
1857
1381
34
인덱스 11과 가장 유사한 6개 인덱스:
11
1920
717
192
1300
405
1150
인덱스 12과 가장 유사한 6개 인덱스:
12
600
955
1946
4
758
82
인덱스 13과 가장 유사한 6개 인덱스:
13
846
1727
1076
1371
903
641
인덱스 14과 가장 유사한 6개 인덱스:
14
1970
1910
1847
1721
1250
740
인덱스 15과 가장 유사한 6개 인덱스:
15
307
1135
1427
748
1352
459
인덱스 16과 가장 유사한 6개 인덱스:
16
1833
470
1938
1942
379
1188
인덱스 17과 가장 유사한 6개 인덱스:
17
1146
1522
1374
1861
636
1565
인덱스 18과 가장 유사한 6개 인덱스:
18
33
1634
143
263
1094
1316
인덱스 19과 가장 유사한 6개 

In [7]:
similar_indices

[array([    0,   546, 13104, 13759,  2063, 10689, 11547], dtype=int64),
 array([   1, 5891,  860, 1275, 3480, 3629, 4422], dtype=int64),
 array([   2, 4614, 6800, 1924, 7422, 7739, 3039], dtype=int64),
 array([    3, 10641, 15331,  1907, 17231, 17452, 17197], dtype=int64),
 array([   4, 7440, 4361, 1614, 4672, 8973, 7983], dtype=int64),
 array([    5, 17714,  3344,  3193,  3059,  3427,  7413], dtype=int64),
 array([    6, 11778, 14800, 10511,  4855, 16635, 10550], dtype=int64),
 array([    7,  4704, 11065,  5767,  1949, 12566,  4174], dtype=int64),
 array([   8, 3824, 1150, 2813, 1069, 7004, 1353], dtype=int64),
 array([    9,   670,  5669,   682, 14230,  8803,  2389], dtype=int64),
 array([  10,  444, 2777, 1189, 8270, 1676, 4011], dtype=int64),
 array([   11, 14876, 15199, 14556, 15353,  8235,  2350], dtype=int64),
 array([   12,  1855, 14916, 15112,  1488, 10994,  1660], dtype=int64),
 array([   13,  6983,  1480,  1966,  2106, 17040, 11618], dtype=int64),
 array([   14,  7377,  5409

In [18]:
import csv
import numpy as np

# 결과를 CSV 파일로 저장
result_file = '테스트_인덱스포함_클러스터6_similar_indices.csv'
with open(result_file, 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['Index'] + list(range(n_similar_indices + 1)))  # 헤더 작성
    for i, indices in enumerate(similar_indices):
        writer.writerow([i] + indices.tolist())  # 인덱스와 유사한 인덱스들 저장

print(f"유사한 인덱스를 {result_file} 파일로 저장했습니다.")


유사한 인덱스를 테스트_인덱스포함_클러스터6_similar_indices.csv 파일로 저장했습니다.
